version: 0.2

env:
  parameter-store:
    AUTH0_DOMAIN: /$ENVIRONMENT_NAME/infra-resource/auth0/domain
    AUTH0_CLIENT_ID: /$ENVIRONMENT_NAME/infra-resource/auth0/client-id
    AUTH0_IDENTIFIER: /$ENVIRONMENT_NAME/infra-resource/auth0/identifier
    MAPBOX_ACCESS_TOKEN: /$ENVIRONMENT_NAME/infra-resource/mapbox/access-token
    GTAG_GA4_MEASUREMENT_ID: /$ENVIRONMENT_NAME/infra-resource/googleanalytics/ga4-measurement-id
    GTAG_UA_MEASUREMENT_ID: /$ENVIRONMENT_NAME/infra-resource/googleanalytics/ua-measurement-id
  variables:
    TARGET: public/gp

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo PreBuild `date`
      - aws --version
      - sam --version
      - npm install
      - sed -i "s#__AUTH0_DOMAIN__#$AUTH0_DOMAIN#" .env.production
      - sed -i "s#__AUTH0_CLIENT_ID__#$AUTH0_CLIENT_ID#" .env.production
      - sed -i "s#__AUTH0_IDENTIFIER__#$AUTH0_IDENTIFIER#" .env.production
      - sed -i "s#__MAPBOX_ACCESS_TOKEN__#$MAPBOX_ACCESS_TOKEN#" .env.production
      - sed -i "s#__GTAG_GA4_MEASUREMENT_ID__#$GTAG_GA4_MEASUREMENT_ID#" .env.production
      - sed -i "s#__GTAG_UA_MEASUREMENT_ID__#$GTAG_UA_MEASUREMENT_ID#" .env.production
  build:
    commands:
      - echo Build `date`
      - npm run build -- --base=/$TARGET/
  post_build:
    commands:
      - echo PostBuild `date`
      - aws s3 sync dist/ s3://$S3_BUCKET/$TARGET/ --delete
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/$TARGET/*"
